(package "fextern"
         "0.1.0"
         "Record file external stats")

(website-url "https://github.com/emacs-vs/fextern")
(keywords "convenience" "externally" "file" "stats")

(package-file "fextern.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "25.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
